// Import comprehensive city data
import { getCityNames } from './indianCities';

// Use comprehensive city list from indianCities.ts
export const commonCities = getCityNames();

export const commonGoodsTypes = [
  'General Cargo', 'Textiles', 'Electronics', 'Machinery', 'Chemicals', 'Food Items',
  'Medicines', 'Automotive Parts', 'Building Materials', 'Agricultural Products',
  'Steel Products', 'Plastic Products', 'Paper Products', 'Rubber Products',
  'Glass Products', 'Ceramic Products', 'Wooden Products', 'Metal Products',
  'Furniture', 'Apparel', 'Footwear', 'Books', 'Stationery', 'Toys', 'Sports Goods',
  'Jewelry', 'Cosmetics', 'Household Items', 'Kitchenware', 'Tools', 'Hardware',
  'Electrical Goods', 'Computer Parts', 'Mobile Accessories', 'Home Appliances',
  'Office Equipment', 'Medical Equipment', 'Industrial Equipment', 'Construction Equipment',
  'Agricultural Equipment', 'Packaging Materials', 'Raw Materials', 'Finished Goods',
  'Spare Parts', 'Components', 'Accessories', 'Liquids', 'Powders', 'Granules',
  'Pellets', 'Sheets', 'Rods', 'Tubes', 'Pipes', 'Wires', 'Cables', 'Fabric',
  'Leather', 'Foam', 'Insulation', 'Filters', 'Gaskets', 'Seals', 'Bearings',
  'Motors', 'Pumps', 'Valves', 'Fittings', 'Fasteners', 'Bolts', 'Nuts',
  'Screws', 'Washers', 'Rivets', 'Clamps', 'Brackets', 'Hinges', 'Handles',
  'Knobs', 'Switches', 'Sockets', 'Plugs', 'Connectors', 'Adapters', 'Converters',
  'Transformers', 'Controllers', 'Sensors', 'Actuators', 'Relays', 'Contactors',
  'Breakers', 'Fuses', 'Surge Protectors', 'UPS', 'Batteries', 'Chargers',
  'Inverters', 'Generators', 'Compressors', 'Fans', 'Blowers', 'Heat Exchangers',
  'Boilers', 'Furnaces', 'Ovens', 'Dryers', 'Coolers', 'Refrigerators',
  'Freezers', 'Air Conditioners', 'Heaters', 'Radiators', 'Pipes', 'Tubes',
  'Hoses', 'Fittings', 'Valves', 'Pumps', 'Tanks', 'Vessels', 'Containers',
  'Drums', 'Barrels', 'Cans', 'Bottles', 'Jars', 'Boxes', 'Cartons', 'Bags',
  'Sacks', 'Wraps', 'Films', 'Sheets', 'Rolls', 'Coils', 'Strips', 'Ribbons',
  'Tapes', 'Labels', 'Tags', 'Stickers', 'Decals', 'Signs', 'Boards',
  'Panels', 'Doors', 'Windows', 'Frames', 'Sills', 'Thresholds', 'Moldings',
  'Trims', 'Baseboards', 'Crown Molding', 'Chair Rails', 'Wainscoting',
  'Beadboard', 'Shiplap', 'Tongue and Groove', 'Plywood', 'OSB', 'MDF',
  'Particle Board', 'Hardboard', 'Softboard', 'Insulation Board', 'Foam Board',
  'Cork Board', 'Bulletin Board', 'Whiteboard', 'Chalkboard', 'Glass Board',
  'Magnetic Board', 'Cork Tiles', 'Vinyl Tiles', 'Ceramic Tiles', 'Porcelain Tiles',
  'Natural Stone', 'Marble', 'Granite', 'Limestone', 'Travertine', 'Slate',
  'Quartz', 'Engineered Stone', 'Laminate', 'Vinyl', 'Linoleum', 'Carpet',
  'Rugs', 'Mats', 'Runners', 'Area Rugs', 'Throw Rugs', 'Bath Mats', 'Door Mats',
  'Kitchen Mats', 'Anti-Fatigue Mats', 'Safety Mats', 'Yoga Mats', 'Exercise Mats',
  'Play Mats', 'Changing Mats', 'Sleeping Mats', 'Camping Mats', 'Picnic Mats',
  'Beach Mats', 'Pool Mats', 'Spa Mats', 'Massage Mats', 'Therapy Mats',
  'Medical Mats', 'Hospital Mats', 'Clinic Mats', 'Dental Mats', 'Veterinary Mats',
  'Laboratory Mats', 'Clean Room Mats', 'ESD Mats', 'Conductive Mats',
  'Anti-Static Mats', 'Static Dissipative Mats', 'Insulating Mats', 'Rubber Mats',
  'Foam Mats', 'Carpet Mats', 'Fabric Mats', 'Vinyl Mats', 'PVC Mats',
  'TPE Mats', 'Silicone Mats', 'Polyurethane Mats', 'Neoprene Mats',
  'Nitrile Mats', 'EPDM Mats', 'Butyl Mats', 'Hypalon Mats', 'Viton Mats',
  'Kalrez Mats', 'Teflon Mats', 'PTFE Mats', 'PFA Mats', 'FEP Mats',
  'ETFE Mats', 'ECTFE Mats', 'PVDF Mats', 'PCTFE Mats', 'PEEK Mats',
  'PEI Mats', 'PPS Mats', 'PES Mats', 'PSU Mats', 'PEK Mats', 'PES Mats'
];

export const commonPackingMethods = [
  'Loose', 'Carton', 'Wooden Box', 'Steel Box', 'Plastic Box', 'Fiber Box',
  'Corrugated Box', 'Cardboard Box', 'Paper Box', 'Metal Box', 'Aluminum Box',
  'Tin Box', 'Glass Box', 'Acrylic Box', 'Plywood Box', 'Particle Board Box',
  'MDF Box', 'Hardboard Box', 'Softboard Box', 'Insulation Box', 'Foam Box',
  'Cork Box', 'Rubber Box', 'Silicone Box', 'Vinyl Box', 'PVC Box',
  'TPE Box', 'Polyurethane Box', 'Neoprene Box', 'Nitrile Box', 'EPDM Box',
  'Butyl Box', 'Hypalon Box', 'Viton Box', 'Kalrez Box', 'Teflon Box',
  'PTFE Box', 'PFA Box', 'FEP Box', 'ETFE Box', 'ECTFE Box', 'PVDF Box',
  'PCTFE Box', 'PEEK Box', 'PEI Box', 'PPS Box', 'PES Box', 'PSU Box',
  'PEK Box', 'Bag', 'Sack', 'Pouch', 'Envelope', 'Wrapper',
  'Cover', 'Case', 'Container', 'Drum', 'Barrel', 'Can', 'Bottle', 'Jar',
  'Tube', 'Cylinder', 'Cone', 'Pyramid', 'Cube', 'Sphere', 'Oval',
  'Rectangular', 'Square', 'Round', 'Oblong', 'Triangular', 'Pentagonal',
  'Hexagonal', 'Octagonal', 'Diamond', 'Star', 'Heart', 'Flower', 'Leaf',
  'Tree', 'Branch', 'Root', 'Seed', 'Fruit', 'Vegetable', 'Grain',
  'Cereal', 'Pulse', 'Legume', 'Nut', 'Berry', 'Herb', 'Spice',
  'Seasoning', 'Flavoring', 'Color', 'Dye', 'Pigment', 'Paint',
  'Varnish', 'Lacquer', 'Enamel', 'Coating', 'Finish', 'Treatment',
  'Process', 'Method', 'Technique', 'Procedure', 'Protocol', 'System',
  'Approach', 'Strategy', 'Plan', 'Scheme', 'Program', 'Project',
  'Initiative', 'Campaign', 'Drive', 'Effort', 'Undertaking', 'Venture',
  'Enterprise', 'Business', 'Company', 'Corporation', 'Organization',
  'Institution', 'Establishment', 'Firm', 'Partnership', 'Sole Proprietorship',
  'Limited Liability Company', 'Public Limited Company', 'Private Limited Company',
  'Holding Company', 'Subsidiary Company', 'Joint Venture', 'Alliance',
  'Collaboration', 'Cooperation', 'Association', 'Society',
  'Club', 'Union', 'Guild', 'Federation', 'Confederation', 'Consortium',
  'Syndicate', 'Cartel', 'Trust', 'Foundation', 'Charity', 'Non-Profit',
  'Non-Governmental Organization', 'Government Organization', 'Public Sector',
  'Private Sector', 'Mixed Economy', 'Capitalist Economy', 'Socialist Economy',
  'Communist Economy', 'Market Economy', 'Planned Economy', 'Command Economy',
  'Free Market', 'Regulated Market', 'Controlled Market', 'Monopoly',
  'Oligopoly', 'Perfect Competition', 'Imperfect Competition', 'Monopolistic Competition'
];
